name: Run Tests

on: push

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-16.04
    container:
      image: perl:5.28.1
    steps:
      - uses: actions/checkout@v4
      - run: prove -r t
