name: Run Tests

on: push

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: perl:5.28.1
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo "deb http://archive.debian.org/debian stretch main contrib non-free" > /etc/apt/sources.list
          apt update -y
          apt install gettext -y
      - name: Run tests
        run: prove -r t
